version: '3'
services:
  sakaba-api:
    build: .
    depends_on:
      - db
    command:
      - go
      - run
      - main.go
    ports:
      - '8080:8080'
    volumes:
      - .:/go/src
    env_file: .env.development
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    env_file: .env.development
